### ISSUE TITLE
Append StyledComponents by d3?

### ISSUE THREAD

**Issue by linonetwo** [Olical/react-faux-dom#125]
Using react-faux-dom, I can
```js
const faux = this.props.connectFauxDOM('div', 'chart');
const svg = select(faux)
      .append('svg')
```
and adding
```css
svg {
  width: 100%;
  width: -webkit-fill-available;
  width: -moz-available;
  height: 100%;
  height: -webkit-fill-available;
  height: -moz-available;
}
```
to it.
Though I prefer something like
```js
const GraphContainer = styled.svg`
  width: 100%;
  width: -webkit-fill-available;
  width: -moz-available;;
  height: 100%;
  height: -webkit-fill-available;
  height: -moz-available;
`;
const svg = select(faux)
      .append(GraphContainer)
```
Can I do this?
